# Generated by Django 2.2.4 on 2023-12-06 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('parent_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.ServiceParent')),
            ],
        ),
        migrations.CreateModel(
            name='ParentLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=25)),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.ServiceChild')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('parent_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.ParentLocations')),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.ServiceChild')),
            ],
        ),
    ]
